'use strict';
const assert = require('node:assert/strict');
const {spawnSync} = require('node:child_process');
const path = require('node:path');
const {install,frame} = require('../scripts/cursor-sync-output.cjs');
const begin='\x1b[?2026h', end='\x1b[?2026l', clear='\x1b[2J';
const writes=[];
const stream={isTTY:true,write(chunk,callback){writes.push(Buffer.from(chunk));callback?.();return false;}};
assert.equal(install(stream),true);
let callbacks=0;
assert.equal(stream.write(clear+'你好\n',()=>callbacks++),false,'Preserve backpressure');
assert.equal(callbacks,1);
assert.equal(writes.pop().toString(),begin+clear+'你好\n'+end);
stream.write(clear+'é\n','latin1',()=>callbacks++);
assert.deepEqual(writes.pop(),Buffer.concat([Buffer.from(begin),Buffer.concat([Buffer.from(clear),Buffer.from([233,10])]),Buffer.from(end)]));
const bytes=Buffer.from('prefix'+clear+'🙂\nsuffix');
const view=bytes.subarray(6,6+Buffer.byteLength(clear+'🙂\n'));
stream.write(view);
assert.deepEqual(writes.pop(),Buffer.concat([Buffer.from(begin),view,Buffer.from(end)]));
stream.write(begin+'widget'+end);
assert.equal(writes.pop().toString(),begin+'widget'+end,'No nested transaction');
stream.write('ordinary line');
assert.equal(writes.pop().toString(),'ordinary line','No rendering changes outside full repaint frames');
const large=Buffer.from(clear+'你好\n'.repeat(50000)+'\x1b]8;;https://example.com/'+ 'x'.repeat(70000)+'\x07link\x1b]8;;\x07\n');
const wrapped=frame(large);
assert.ok(wrapped.toString().split(begin).length>3,'Refresh sync deadline during large frames');
assert.deepEqual(Buffer.from(wrapped.toString().split(begin).join('').split(end).join('')),large,'Original ANSI, Unicode and hyperlinks stay byte-for-byte intact');
assert.ok(wrapped.includes(Buffer.from('\x1b]8;;https://example.com/'+ 'x'.repeat(70000)+'\x07')),'Never inject a refresh inside OSC');
const redirected={write(){}};const saved=redirected.write;
assert.equal(install(redirected),false);assert.equal(redirected.write,saved);
const hook=path.resolve(__dirname,'../scripts/cursor-sync-output.cjs');
const child=spawnSync(process.execPath,['-e',`process.stdout.write(JSON.stringify({once:process.env.SILING_CURSOR_SYNC_ONCE,options:process.env.NODE_OPTIONS}))`],{encoding:'utf8',env:{...process.env,SILING_CURSOR_SYNC_ONCE:'1',SILING_CURSOR_PREVIOUS_NODE_OPTIONS:'--no-warnings',NODE_OPTIONS:`--no-warnings --require="${hook}"`}});
assert.equal(child.status,0,child.stderr);
assert.deepEqual(JSON.parse(child.stdout),{options:'--no-warnings'},'Child env preserves user options but removes preload and marker');
console.log('PASS: atomic Cursor writes, UTF-8/binary, callbacks, backpressure, native transactions and child environment');
