import assert from 'node:assert/strict';
export async function checkFork({evaluate,waitFor,cdp,viewport,screenshot,mode,submissions,release}) {
  await viewport(1280,800);
  await evaluate(`localStorage.setItem('orch_layout','cols-2x2');localStorage.setItem('orch_slots',JSON.stringify(['fixture-1','fixture-2','fixture-3','fixture-4']));`);
  await cdp('Page.reload');
  await waitFor(`!!document.querySelector('[data-run-id="fixture-1"] iframe')?.contentDocument?.querySelector('textarea')`);
  await evaluate(`window.forkOriginalFrame=document.querySelector('[data-run-id="fixture-1"] iframe');document.querySelector('[data-run-id="fixture-1"] .pane-input textarea').value='keep this draft';document.querySelector('[data-run-id="fixture-1"] .btn-pane-more').click();document.querySelector('[data-run-id="fixture-1"] .btn-fork-pane').click()`);
  await waitFor(`document.querySelector('#fork-pane-dialog').open`);
  assert.equal(await evaluate(`document.querySelectorAll('.pane-menu[open]').length`),0);
  assert.equal(await evaluate(`document.querySelector('#fork-pane-kind').value`),'conversation');
  const initial=submissions.length;
  await evaluate(`document.querySelector('#fork-pane-dialog [data-fork-close]').click()`);
  assert.equal(submissions.length,initial,'Cancel never launches');
  await evaluate(`document.querySelector('[data-run-id="fixture-1"] .btn-pane-more').click();document.querySelector('[data-run-id="fixture-1"] .btn-fork-pane').click()`);
  await waitFor(`document.querySelector('#fork-pane-dialog').open`);
  mode('failure');
  await evaluate(`document.querySelector('#fork-pane-dialog form').requestSubmit()`);
  await waitFor(`!document.querySelector('#fork-pane-error').hidden && !document.querySelector('#fork-pane-dialog').hasAttribute('aria-busy')`);
  const requestId=submissions.at(-1).request_id;
  mode('delay');
  await evaluate(`document.querySelector('#fork-pane-dialog form').requestSubmit();document.querySelector('#fork-pane-dialog form').requestSubmit()`);
  for(let i=0;i<60&&submissions.length<initial+2;i++)await new Promise(r=>setTimeout(r,50));
  assert.equal(submissions.length,initial+2,'Double click sends only one pending request');
  assert.equal(submissions.at(-1).request_id,requestId,'Retry keeps idempotency identity');
  await screenshot('fork-pending');
  release();
  await waitFor(`!document.querySelector('#fork-pane-dialog').open`);
  await waitFor(`!!document.querySelector('[data-run-id="fixture-fork"] iframe')`);
  assert.equal(await evaluate(`document.querySelector('[data-run-id="fixture-1"] iframe')===forkOriginalFrame`),true,'Fork preserves source transport');
  assert.equal(await evaluate(`document.querySelector('[data-run-id="fixture-1"] .pane-input textarea').value`),'keep this draft');
  const slots=await evaluate(`JSON.parse(localStorage.getItem('orch_slots'))`);
  assert.ok(slots.includes('fixture-1')&&slots.includes('fixture-fork'));
  assert.equal(slots.length,6,'A full 2x2 grid expands without evicting a pane');
  await evaluate(`document.querySelector('[data-run-id="fixture-3"] .btn-pane-more').click();document.querySelector('[data-run-id="fixture-3"] .btn-fork-pane').click()`);
  await waitFor(`document.querySelector('#fork-pane-dialog').open`);
  assert.equal(await evaluate(`document.querySelector('#fork-pane-kind').value`),'configuration');
  assert.equal(await evaluate(`document.querySelector('#fork-pane-kind [value="conversation"]').disabled`),true,'Cursor cannot silently resume a shared conversation');
  await evaluate(`{const language=document.querySelector('[data-appearance="language"]');language.value='zh';language.dispatchEvent(new Event('change'));}`);
  await viewport(860,740);
  assert.equal(await evaluate(`document.querySelector('#fork-pane-heading').textContent`),'Fork 到新面板');
  await screenshot('fork-chinese');
  await evaluate(`document.querySelector('#fork-pane-dialog [data-fork-close]').click()`);
  console.log('PASS: fork cancellation, retry identity, duplicate prevention, independent pane, grid growth, original iframe/draft and unsupported native fork');
}
