import assert from 'node:assert/strict';

export async function checkMobileCompose({evaluate,waitFor,viewport,screenshot,pause,cdp,requests,inputs,sessions,mode,delayed,release}) {
  await viewport(390,844);
  await waitFor(`!!document.querySelector('#mobile-reader-reply')`);
  await evaluate(`window.confirm=()=>true;window.composePrompt=window.prompt;window.prompt=()=>{throw Error('Input must not replay after auth')};
    document.querySelector('#mobile-reader-search').value='';document.querySelector('#mobile-reader-search').dispatchEvent(new Event('input'));
    document.querySelector('#mobile-reader-filter').value='all';document.querySelector('#mobile-reader-filter').dispatchEvent(new Event('change'))`);
  const prefs=await evaluate(`['orch_layout','orch_slots','orch_tty'].map(k=>localStorage.getItem(k))`);
  const start=requests.length, tty=()=>requests.filter(r=>r.path.endsWith('/tty')).length, ttyBefore=tty();
  const open = async id => {
    await waitFor(`!!document.querySelector('#mobile-reader-list [data-run-id="${id}"]')`);
    await evaluate(`document.querySelector('#mobile-reader-list [data-run-id="${id}"]').click();document.querySelector('#mobile-reader-reply').click()`);
    await waitFor(`!document.querySelector('#mobile-compose').hidden`);
  };
  const draft=()=>evaluate(`document.querySelector('#mobile-compose-text').value`);
  const write=value=>evaluate(`document.querySelector('#mobile-compose-text').value=${JSON.stringify(value)};document.querySelector('#mobile-compose-text').dispatchEvent(new Event('input'))`);
  const send=()=>evaluate(`document.querySelector('#mobile-compose-send').click()`);
  const back=()=>evaluate(`document.querySelector('#mobile-reader-back').click()`);
  await open('fixture-0'); await write('  中文\nsecond 😀\n');
  await evaluate(`document.querySelector('#mobile-reader-files').click()`);
  await waitFor(`document.querySelector('#folder-modal').hidden===false`);
  await evaluate(`document.querySelector('#folder-modal-close').click()`);
  assert.equal(await draft(),'  中文\nsecond 😀\n');
  await back();await open('fixture-1');assert.equal(await draft(),'');await write('other draft');
  await back();await open('fixture-0');assert.equal(await draft(),'  中文\nsecond 😀\n');
  mode('delay');await send();await send();
  await waitFor(`document.querySelector('#mobile-compose-send').disabled`);
  for(let i=0;i<50&&!delayed();i++)await pause(50);
  assert.equal(inputs.length,1,'Double click submits only once');
  assert.deepEqual(inputs[0],{path:'/api/sessions/fixture-0/input',body:{text:'  中文\nsecond 😀\n'}});
  await back();await open('fixture-1');release();mode('ok');await pause(100);
  assert.equal(await draft(),'other draft','Late A reply never clears B');
  await back();await open('fixture-0');assert.equal(await draft(),'');
  assert.match(await evaluate(`document.querySelector('#mobile-compose-status').textContent`),/accepted.*execution/i);
  await write('keep unknown');mode('auth');await send();
  await waitFor(`document.querySelector('#mobile-compose').dataset.delivery==='uncertain'`);
  assert.equal(await draft(),'keep unknown');
  await evaluate(`window.prompt=window.composePrompt;delete window.composePrompt`);
  const before=inputs.length;await send();await pause(100);assert.equal(inputs.length,before);
  await evaluate(`window.confirm=()=>false;document.querySelector('#mobile-compose-review').click()`);
  assert.equal(await evaluate(`document.querySelector('#mobile-compose').dataset.delivery`),'uncertain');
  await evaluate(`window.confirm=()=>true;document.querySelector('#mobile-compose-review').click()`);
  await evaluate(`Object.defineProperty(navigator,'onLine',{configurable:true,value:false});window.dispatchEvent(new Event('offline'))`);
  await send();assert.equal(inputs.length,before);assert.equal(await draft(),'keep unknown');
  await evaluate(`delete navigator.onLine;window.dispatchEvent(new Event('online'))`);
  mode('ok');await pause(100);assert.equal(inputs.length,before,'Reconnect never resends');
  await send();await waitFor(`document.querySelector('#mobile-compose-text').value===''`);
  await write('new draft');
  await evaluate(`document.querySelector('#mobile-compose-key-Escape').click()`);
  await waitFor(`!document.querySelector('#mobile-compose-send').disabled`);
  assert.deepEqual(inputs.at(-1).body,{key:'Escape'});assert.equal(await draft(),'new draft');
  await evaluate(`window.confirm=()=>false;document.querySelector('#mobile-compose-key-C-c').click()`);await pause(100);
  assert.deepEqual(inputs.at(-1).body,{key:'Escape'});
  await evaluate(`window.confirm=()=>true;document.querySelector('#mobile-compose-key-C-c').click()`);
  await waitFor(`!document.querySelector('#mobile-compose-send').disabled`);
  assert.deepEqual(inputs.at(-1).body,{key:'C-c'});
  await evaluate(`document.querySelector('#mobile-compose-key-Tab').click()`);
  await waitFor(`!document.querySelector('#mobile-compose-send').disabled`);
  assert.deepEqual(inputs.at(-1).body,{key:'Tab'});
  const beforeKeyboard=inputs.length;
  await write('IME 中文');
  await evaluate(`document.querySelector('#mobile-compose-text').focus();document.querySelector('#mobile-compose-text').setSelectionRange(6,6)`);
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});
  await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  assert.equal(await draft(),'IME 中文\n','Enter inserts a newline, never submits');
  await evaluate(`document.querySelector('#mobile-compose-text').dispatchEvent(new CompositionEvent('compositionstart',{data:'中'}));document.querySelector('#mobile-compose-text').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));document.querySelector('#mobile-compose-text').dispatchEvent(new CompositionEvent('compositionend',{data:'中文'}))`);
  assert.equal(inputs.length,beforeKeyboard,'Composition Enter never sends');
  for(const width of [360,390,430,780]) {
    await viewport(width,width===780?390:844);
    assert.ok(await evaluate(`document.documentElement.scrollWidth<=innerWidth`));
    assert.ok(await evaluate(`document.querySelector('#mobile-compose-send').getBoundingClientRect().height>=44`));
    await screenshot('mobile-compose-'+width);
  }
  await viewport(390,844);
  // A reduced visual viewport models the keyboard, not a real iOS keyboard.
  await evaluate(`Object.defineProperty(visualViewport,'height',{configurable:true,value:400});visualViewport.dispatchEvent(new Event('resize'))`);
  await waitFor(`document.querySelector('.app').getBoundingClientRect().height<=400`);
  assert.ok(await evaluate(`document.querySelector('#mobile-compose-send').getBoundingClientRect().bottom<=400`),'Send remains inside the keyboard-sized viewport');
  await screenshot('mobile-compose-keyboard-sized');
  await evaluate(`delete visualViewport.height;visualViewport.dispatchEvent(new Event('resize'))`);
  mode('delay');await send();
  for(let i=0;i<50&&!delayed();i++)await pause(50);
  assert.ok(delayed());
  const pendingCount=inputs.length;
  await cdp('Page.reload');
  await waitFor(`!!document.querySelector('#mobile-reader-list [data-run-id="fixture-0"]')`);
  release(); mode('ok'); await open('fixture-0');
  assert.equal(await draft(),'IME 中文\n');
  assert.equal(await evaluate(`document.querySelector('#mobile-compose').dataset.delivery`),'uncertain','Pending at reload is unknown, never silently sent again');
  assert.equal(inputs.length,pendingCount);
  await evaluate(`window.confirm=()=>true;document.querySelector('#mobile-compose-review').click()`);
  mode('delay');await send();
  for(let i=0;i<50&&!delayed();i++)await pause(50);
  const timeoutCount=inputs.length;
  await pause(12100);
  await waitFor(`document.querySelector('#mobile-compose').dataset.delivery==='uncertain'`);
  release();mode('ok');await pause(100);
  assert.equal(inputs.length,timeoutCount,'Timeout never retries');
  assert.equal(await draft(),'IME 中文\n','Late timed-out response cannot clear the draft');
  await evaluate(`document.querySelector('#mobile-compose-review').click()`);
  mode('delay');await send();
  for(let i=0;i<50&&!delayed();i++)await pause(50);
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`);
  await waitFor(`document.querySelector('#mobile-compose').dataset.delivery==='uncertain'`);
  const hiddenCount=inputs.length;
  release();mode('ok');
  await evaluate(`delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))`);
  await pause(100);assert.equal(inputs.length,hiddenCount,'Foreground return does not replay input');
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='zh';c.dispatchEvent(new Event('change'));document.documentElement.dataset.appTheme='light';}`);
  await screenshot('mobile-compose-uncertain-zh-light');
  assert.match(await evaluate(`document.querySelector('#mobile-compose-status').textContent`),/结果未知/);
  await evaluate(`window.composeSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('siling_mobile_draft_v1:'))throw Error('fixture quota');return composeSetItem.call(this,k,v)}`);
  await write('memory only');
  assert.equal(await evaluate(`document.querySelector('#mobile-compose-storage').hidden`),false);
  await back();await open('fixture-1');assert.equal(await draft(),'other draft');
  await back();await open('fixture-0');assert.equal(await draft(),'memory only');
  await evaluate(`Storage.prototype.setItem=composeSetItem;delete window.composeSetItem`);
  await back();await open('fixture-4');
  assert.ok(await evaluate(`document.querySelector('#mobile-compose-send').disabled && document.querySelector('#mobile-compose-key-Escape').disabled`),'Offline remote input is disabled');
  await back();
  const previousAlive=sessions[3].alive; sessions[3].alive=false;
  await evaluate(`document.querySelector('#btn-refresh').click()`);
  await pause(150);await open('fixture-3');await write('ended draft');
  assert.ok(await evaluate(`document.querySelector('#mobile-compose-send').disabled`),'Ended execution cannot receive input');
  sessions[3].alive=previousAlive;
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='en';c.dispatchEvent(new Event('change'));document.documentElement.dataset.appTheme='dark';}`);
  assert.deepEqual(await evaluate(`['orch_layout','orch_slots','orch_tty'].map(k=>localStorage.getItem(k))`),prefs);
  assert.equal(tty(),ttyBefore,'Reply never attaches a terminal');
  assert.equal(requests.slice(start).some(r=>/\/(send|stop|restart|resume|kill)$/.test(r.path)),false);
  await back();
  console.log('PASS: mobile multiline drafts, Files/back isolation, exact target, duplicate/auth/offline protection, explicit keys and narrow layouts');
}
