import assert from 'node:assert/strict';
export async function checkRename({evaluate,waitFor,viewport,screenshot,cdp,mode,submissions,release,pending}) {
  await evaluate(`window.renameFrame=document.querySelector('[data-run-id="fixture-0"] iframe');window.savedPrompt=window.prompt;window.prompt=()=>{throw Error('prompt() is not supported.')};document.querySelector('.session-item[data-id="fixture-0"] .btn-rename').click()`);
  await waitFor(`document.querySelector('#rename-session-dialog').open`);
  assert.equal(await evaluate(`document.activeElement.id`),'rename-session-name');
  const before=submissions.length;
  await evaluate(`document.querySelector('#rename-session-name').value='cancel me';document.querySelector('#rename-session-dialog [data-rename-cancel]').click()`);
  assert.equal(submissions.length,before,'Cancel sends no rename request');
  await evaluate(`document.querySelector('[data-run-id="fixture-0"] .btn-pane-more').click();document.querySelector('[data-run-id="fixture-0"] .btn-rename-session').click()`);
  await waitFor(`document.querySelector('#rename-session-dialog').open`);
  assert.equal(await evaluate(`!!document.querySelector('.pane-menu[open]')`),false,'More closes before rename dialog opens');
  mode('error');
  await evaluate(`document.querySelector('#rename-session-name').value='Named <literal>';document.querySelector('#rename-session-dialog form').requestSubmit()`);
  await waitFor(`!document.querySelector('#rename-session-error').hidden`);
  assert.equal(await evaluate(`document.querySelector('#rename-session-name').value`),'Named <literal>','Failure preserves the draft');
  mode('delay');
  await evaluate(`document.querySelector('#rename-session-dialog form').requestSubmit();document.querySelector('#rename-session-dialog form').requestSubmit()`);
  await waitFor(`document.querySelector('#rename-session-dialog').getAttribute('aria-busy')==='true'`);
  for(let i=0;i<80&&!pending();i++) await new Promise(r=>setTimeout(r,25));
  assert.ok(pending(),'Fixture receives the pending request');
  assert.equal(submissions.length,before+2,'A pending rename cannot be submitted twice');
  release();
  await waitFor(`!document.querySelector('#rename-session-dialog').open`);
  await waitFor(`document.querySelector('[data-run-id="fixture-0"] .title').textContent==='Named <literal>'`);
  assert.ok(await evaluate(`document.querySelector('.session-item[data-id="fixture-0"]').textContent.includes('Named <literal>')`),'Sidebar title updates');
  assert.equal(await evaluate(`document.querySelector('[data-run-id="fixture-0"] iframe')===renameFrame`),true,'Rename preserves the terminal iframe');
  mode('ok');
  await evaluate(`document.querySelector('.session-item[data-id="fixture-0"] .btn-rename').click()`);
  assert.equal(await evaluate(`document.querySelector('#rename-session-name').value`),'Named <literal>','Existing label is editable');
  await viewport(390,844);
  assert.ok(await evaluate(`(()=>{const r=document.querySelector('#rename-session-dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})()`),'Dialog fits narrow screens');
  await screenshot('rename-session-mobile');
  await viewport(1280,800);
  await evaluate(`document.querySelector('#rename-session-name').value='';document.querySelector('#rename-session-dialog form').requestSubmit()`);
  await waitFor(`!document.querySelector('#rename-session-dialog').open`);
  assert.equal(submissions.at(-1).label,'','Empty label restores the automatic title');
  await evaluate(`{const language=document.querySelector('[data-appearance="language"]');language.value='zh';language.dispatchEvent(new Event('change'));document.querySelector('[data-run-id="fixture-0"] .btn-pane-more').click();document.querySelector('[data-run-id="fixture-0"] .btn-rename-session').click();}`);
  await waitFor(`document.querySelector('#rename-session-dialog').open`);
  assert.equal(await evaluate(`document.querySelector('#rename-session-heading').textContent`),'重命名会话');
  await screenshot('rename-session-chinese');
  const beforeEscape=submissions.length;
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  await waitFor(`!document.querySelector('#rename-session-dialog').open`);
  assert.equal(submissions.length,beforeEscape,'Escape cancels without saving');
  await evaluate(`{const language=document.querySelector('[data-appearance="language"]');language.value='en';language.dispatchEvent(new Event('change'));window.prompt=savedPrompt;}`);

  console.log('PASS: shared rename dialog, unsupported native prompt, cancel, failure/retry, pending guard, literal titles and narrow layout');
}
