import assert from 'node:assert/strict';

export async function checkResources({evaluate, waitFor, viewport, screenshot, pause, cdp,
                                     requests, mode, delayed, frameLoads}) {
  await viewport(1280, 900);
  await pause(1200);
  assert.ok(await evaluate(`!!document.querySelector('#resource-summary')?.getClientRects().length`), 'Main view exposes resource observations without opening a dialog');
  await waitFor(`document.querySelector('[data-summary-metric="cpu"] strong').textContent==='37.5%'`);
  assert.equal(await evaluate(`document.querySelector('#resource-dialog').open`), false);
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="memory"] strong').textContent`), '75%');
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="outputs_disk"] strong').textContent`), '50%');
  assert.equal(await evaluate(`document.querySelector('#resource-summary').dataset.status`), 'partial', 'Missing project-volume observations are not silently marked healthy');
  assert.ok(await evaluate(`document.querySelector('#resource-summary').getBoundingClientRect().bottom<=document.querySelector('#grid').getBoundingClientRect().top`), 'Summary does not overlap pane content');
  await screenshot('resources-summary-desktop');
  const frames = frameLoads();
  const requestStart = requests.length;
  await evaluate(`document.querySelector('#resource-summary').focus()`);
  await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Enter', code:'Enter', windowsVirtualKeyCode:13, text:'\r'});
  await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Enter', code:'Enter', windowsVirtualKeyCode:13});
  await waitFor(`document.querySelector('#resource-dialog').open`);
  await evaluate(`document.querySelector('#resource-dialog').close()`);
  await waitFor(`document.activeElement.id==='resource-summary'`);
  await evaluate(`document.documentElement.dataset.appTheme='dark'`);
  await screenshot('resources-summary-desktop-dark');
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='en';c.dispatchEvent(new Event('change'));document.querySelector('#btn-workspace-menu').click();document.querySelector('#btn-resources').click();}`);
  await waitFor(`document.querySelector('[data-metric="cpu"] strong').textContent==='37.5%'`);
  assert.equal(await evaluate(`document.querySelector('#resource-host literal')`), null);
  assert.match(await evaluate(`document.querySelector('#resource-host').textContent`), /fixture-host <literal>/);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`), '2 GiB / 8 GiB');
  assert.equal(await evaluate(`document.querySelector('[data-metric="projects_disk"]').dataset.status`), 'unknown');
  assert.equal(await evaluate(`document.querySelector('[data-metric="projects_disk"] strong').textContent`), '—');
  await screenshot('resources-desktop-en');
  mode('warming_up');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"] p').textContent.includes('Waiting for two CPU samples')`);
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="cpu"] strong').textContent`), '—');
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="memory"]').dataset.status`), 'fresh');
  mode('zero');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-summary-metric="cpu"] strong').textContent==='0%'`);
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="cpu"]').dataset.status`), 'fresh', 'Genuine zero observations are distinct from missing samples');
  mode('dependency_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('Install requirements.txt')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="cpu"] strong').textContent`), '—');
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="cpu"] strong').textContent`), '—', 'Missing samples must not look like zero load');
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="cpu"]').dataset.status`), 'unavailable');
  assert.match(await evaluate(`document.querySelector('[data-metric="cpu"] p').textContent`), /Missing dependency: psutil/);
  await screenshot('resources-missing-dependency-en');
  mode('dependency_unavailable');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"] p').textContent.includes('Cannot load psutil')`);
  mode('path_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="projects_disk"] p').textContent.includes('Configured directory does not exist')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"]').dataset.status`), 'fresh');
  mode('error');
  const before = await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`);
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('failed')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"]').dataset.status`), 'unavailable');
  await evaluate(`window.resourceClock=Date.now;Date.now=()=>resourceClock()+16000`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='stale'`);
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="memory"]').dataset.status`), 'stale');
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('[data-summary-metric="memory"] .resource-ring')).backgroundImage`), 'none', 'Expired readings lose their live ring');
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`), before);
  await screenshot('resources-stale');
  await evaluate(`Date.now=resourceClock;delete window.resourceClock`);
  mode('disabled');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"]').dataset.status==='disabled'`);
  assert.equal(await evaluate(`document.querySelector('#resource-summary').dataset.status`), 'disabled');
  assert.equal(await evaluate(`document.querySelector('[data-summary-metric="cpu"] strong').textContent`), '—');
  mode('healthy');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"]').dataset.status==='fresh'`);
  assert.equal(await evaluate(`document.querySelector('#resource-summary').dataset.status`), 'fresh');
  assert.match(await evaluate(`document.querySelector('.resource-summary-heading small').textContent`), /Every 5s/);
  mode('unauthorized');
  await evaluate(`window.resourcePrompt=window.prompt;window.prompt=()=>{throw Error('Resource polling must not prompt')};document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('failed')`);
  await evaluate(`window.prompt=window.resourcePrompt;delete window.resourcePrompt`);
  mode('ok');
  await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Escape', code:'Escape', windowsVirtualKeyCode:27});
  await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Escape', code:'Escape', windowsVirtualKeyCode:27});
  await waitFor(`!document.querySelector('#resource-dialog').open`);
  await waitFor(`document.activeElement.id==='btn-workspace-menu'`);
  const count = () => requests.filter(r=>r.path==='/api/resources').length;
  const closedCount = count();
  await pause(5300);
  assert.equal(count(), closedCount + 1, 'Closed details retain exactly one five-second summary polling loop');
  await waitFor(`document.querySelector('[data-summary-metric="cpu"]').dataset.status==='fresh'`);
  assert.equal(frameLoads(), frames, 'Resource inspection never reloads desktop terminals');
  assert.equal(requests.slice(requestStart).some(r=>r.method==='POST'), false, 'Resource view is read-only');

  await viewport(390, 844);
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='zh';c.dispatchEvent(new Event('change'));document.documentElement.dataset.appTheme='light';}`);
  await waitFor(`document.querySelector('.resource-summary-heading strong').textContent==='主机资源'`);
  await screenshot('resources-summary-mobile-zh-light');
  await viewport(320, 740);
  assert.ok(await evaluate(`document.documentElement.scrollWidth<=innerWidth && document.querySelector('#resource-summary').scrollWidth<=document.querySelector('#resource-summary').clientWidth`), 'Summary fits a narrow phone');
  assert.ok(await evaluate(`document.querySelector('#resource-summary').getBoundingClientRect().height>=44`));
  await screenshot('resources-summary-mobile-320');
  await viewport(390, 844);
  assert.ok(await evaluate(`document.querySelector('#btn-resources-mobile').getClientRects().length>0`), 'Phone has a visible resource entry, independent of hidden Workspace');
  assert.ok(await evaluate(`document.querySelector('#btn-resources-mobile').getBoundingClientRect().width>=44`));
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='zh';c.dispatchEvent(new Event('change'));document.documentElement.dataset.appTheme='light';document.querySelector('#btn-resources-mobile').click();}`);
  await waitFor(`document.querySelector('#resource-title').textContent==='主机资源'`);
  assert.ok(await evaluate(`document.documentElement.scrollWidth<=innerWidth && document.querySelector('#resource-dialog').scrollWidth<=document.querySelector('#resource-dialog').clientWidth`));
  assert.ok(await evaluate(`document.querySelector('#resource-refresh').getBoundingClientRect().height>=44`));
  assert.match(await evaluate(`document.querySelector('#resource-dialog').textContent`), /不等于压力判定/);
  await screenshot('resources-mobile-zh-light');
  await waitFor(`!document.querySelector('#resource-refresh').disabled`);
  mode('dependency_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('资源采集器缺少 psutil')`);
  await screenshot('resources-missing-dependency-zh');
  mode('ok');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='fresh'`);
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));window.resourceClock=Date.now;Date.now=()=>resourceClock()+16000`);
  const hiddenCount = count();
  await pause(5300);
  assert.equal(count(), hiddenCount, 'Hidden pages stop polling even with details open');
  mode('error');
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='stale'`);
  await evaluate(`Date.now=resourceClock;delete window.resourceClock;delete document.hidden`);
  await waitFor(`!document.querySelector('#resource-refresh').disabled`);
  mode('delay');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  for (let i=0;i<50&&!delayed();i++) await pause(50);
  assert.ok(delayed());
  await evaluate(`document.querySelector('#resource-dialog').close()`);
  delayed()(); mode('ok');
  await pause(100);
  assert.equal(await evaluate(`document.querySelector('#resource-dialog').open`), false);
  await waitFor(`document.activeElement.id==='btn-resources-mobile'`);
  // Invalid payload after closing cannot turn the summary into a live display.
  assert.equal(await evaluate(`document.querySelector('#resource-summary').dataset.status`), 'unavailable');
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))`);
  const hiddenClosedCount = count();
  await pause(5300);
  assert.equal(count(), hiddenClosedCount, 'Background polling also stops with details closed');
  await evaluate(`delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))`);
  await waitFor(`document.querySelector('[data-summary-metric="cpu"]').dataset.status==='fresh'`);
  console.log('PASS: main resource summary, meters, shared bounded polling, literal values, units, partial/failed/expired/disabled samples, bilingual narrow layouts, focus and no terminal reload/control');
}
