import assert from 'node:assert/strict';

export async function checkResources({evaluate, waitFor, viewport, screenshot, pause, cdp,
                                     requests, mode, delayed, frameLoads}) {
  await viewport(1280, 900);
  await pause(1200);
  const frames = frameLoads();
  const requestStart = requests.length;
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='en';c.dispatchEvent(new Event('change'));document.querySelector('#btn-workspace-menu').click();document.querySelector('#btn-resources').click();}`);
  await waitFor(`document.querySelector('[data-metric="cpu"] strong').textContent==='37.5%'`);
  assert.equal(await evaluate(`document.querySelector('#resource-host literal')`), null);
  assert.match(await evaluate(`document.querySelector('#resource-host').textContent`), /fixture-host <literal>/);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`), '2 GiB / 8 GiB');
  assert.equal(await evaluate(`document.querySelector('[data-metric="projects_disk"]').dataset.status`), 'unknown');
  assert.equal(await evaluate(`document.querySelector('[data-metric="projects_disk"] strong').textContent`), '—');
  await screenshot('resources-desktop-en');
  mode('dependency_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('Install requirements.txt')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="cpu"] strong').textContent`), '—');
  assert.match(await evaluate(`document.querySelector('[data-metric="cpu"] p').textContent`), /Missing dependency: psutil/);
  await screenshot('resources-missing-dependency-en');
  mode('dependency_unavailable');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"] p').textContent.includes('Cannot load psutil')`);
  mode('path_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="projects_disk"] p').textContent.includes('Configured directory does not exist')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"]').dataset.status`), 'fresh');
  mode('error');
  const before = await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`);
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('failed')`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"]').dataset.status`), 'unavailable');
  await evaluate(`window.resourceClock=Date.now;Date.now=()=>resourceClock()+16000`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='stale'`);
  assert.equal(await evaluate(`document.querySelector('[data-metric="memory"] strong').textContent`), before);
  await screenshot('resources-stale');
  await evaluate(`Date.now=resourceClock;delete window.resourceClock`);
  mode('disabled');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"]').dataset.status==='disabled'`);
  mode('ok');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="cpu"]').dataset.status==='fresh'`);
  mode('unauthorized');
  await evaluate(`window.resourcePrompt=window.prompt;window.prompt=()=>{throw Error('Resource polling must not prompt')};document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('failed')`);
  await evaluate(`window.prompt=window.resourcePrompt;delete window.resourcePrompt`);
  mode('ok');
  await cdp('Input.dispatchKeyEvent', {type:'keyDown', key:'Escape', code:'Escape', windowsVirtualKeyCode:27});
  await cdp('Input.dispatchKeyEvent', {type:'keyUp', key:'Escape', code:'Escape', windowsVirtualKeyCode:27});
  await waitFor(`!document.querySelector('#resource-dialog').open`);
  await waitFor(`document.activeElement.id==='btn-workspace-menu'`);
  assert.equal(frameLoads(), frames, 'Resource inspection never reloads desktop terminals');
  assert.equal(requests.slice(requestStart).some(r=>r.method==='POST'), false, 'Resource view is read-only');

  await viewport(390, 844);
  assert.ok(await evaluate(`document.querySelector('#btn-resources-mobile').getClientRects().length>0`), 'Phone has a visible resource entry, independent of hidden Workspace');
  assert.ok(await evaluate(`document.querySelector('#btn-resources-mobile').getBoundingClientRect().width>=44`));
  await evaluate(`{const c=document.querySelector('[data-appearance="language"]');c.value='zh';c.dispatchEvent(new Event('change'));document.documentElement.dataset.appTheme='light';document.querySelector('#btn-resources-mobile').click();}`);
  await waitFor(`document.querySelector('#resource-title').textContent==='主机资源'`);
  assert.ok(await evaluate(`document.documentElement.scrollWidth<=innerWidth && document.querySelector('#resource-dialog').scrollWidth<=document.querySelector('#resource-dialog').clientWidth`));
  assert.ok(await evaluate(`document.querySelector('#resource-refresh').getBoundingClientRect().height>=44`));
  assert.match(await evaluate(`document.querySelector('#resource-dialog').textContent`), /不等于压力判定/);
  await screenshot('resources-mobile-zh-light');
  await waitFor(`!document.querySelector('#resource-refresh').disabled`);
  mode('dependency_missing');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('#resource-notice').textContent.includes('资源采集器缺少 psutil')`);
  await screenshot('resources-missing-dependency-zh');
  mode('ok');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='fresh'`);
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));window.resourceClock=Date.now;Date.now=()=>resourceClock()+16000`);
  mode('error');
  await evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))`);
  await waitFor(`document.querySelector('[data-metric="memory"]').dataset.status==='stale'`);
  await evaluate(`Date.now=resourceClock;delete window.resourceClock;delete document.hidden`);
  await waitFor(`!document.querySelector('#resource-refresh').disabled`);
  mode('delay');
  await evaluate(`document.querySelector('#resource-refresh').click()`);
  for (let i=0;i<50&&!delayed();i++) await pause(50);
  assert.ok(delayed());
  await evaluate(`document.querySelector('#resource-dialog').close()`);
  delayed()(); mode('ok');
  await pause(100);
  assert.equal(await evaluate(`document.querySelector('#resource-dialog').open`), false);
  await waitFor(`document.activeElement.id==='btn-resources-mobile'`);
  console.log('PASS: host resources, literal values, units, partial/failed/expired/disabled samples, bilingual layouts, focus and no terminal reload/control');
}
