import assert from 'node:assert/strict';

export async function checkSessionHelp({evaluate,waitFor,viewport,cdp,screenshot,pause,requests}) {
  await waitFor(`!!document.querySelector('#btn-new')`);
  await viewport(1280,900);
  await waitFor(`document.querySelectorAll('.pane iframe').length===4 && [...document.querySelectorAll('.pane iframe')].every(f=>f.contentDocument?.querySelector('textarea'))`);
  await evaluate(`{const lang=document.querySelector('[data-appearance="language"]');lang.value='en';lang.dispatchEvent(new Event('change'));}document.querySelector('#btn-new').click();window.helpFrames=[...document.querySelectorAll('.pane iframe')];`);
  await pause(100);
  const writes=requests.filter(r=>r.method==='POST').length;
  assert.equal(await evaluate(`document.querySelector('#new-standard-help').hidden`),true);
  assert.equal(await evaluate(`document.querySelector('#new-modal .modal-body').textContent.includes('Original transcripts')`),false,'Long instructions leave the form');
  const point=()=>evaluate(`(()=>{const r=document.querySelector('#new-standard-help-toggle').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};})()`);
  await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',...await point()});
  await waitFor(`!document.querySelector('#new-standard-help').hidden`);
  const text=await evaluate(`document.querySelector('#new-standard-help').textContent`);
  for(const heading of ['Resume','Import existing','Terminal','Open iTerm & Start','Start in background']) assert.ok(text.includes(heading));
  assert.ok(/running\s+siling run/.test(text),'Command spacing is readable');
  assert.ok(/or\s+tmux attach/.test(text));
  await screenshot('new-session-help-hover');
  await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:10,y:10});
  await waitFor(`document.querySelector('#new-standard-help').hidden`);
  await evaluate(`document.querySelector('#new-standard-help-toggle').focus()`);
  await waitFor(`!document.querySelector('#new-standard-help').hidden`);
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  assert.equal(await evaluate(`document.querySelector('#new-standard-help').hidden && !document.querySelector('#new-modal').hidden`),true,'Escape dismisses help before the form');
  await evaluate(`document.querySelector('#new-close').click();{const lang=document.querySelector('[data-appearance="language"]');lang.value='zh';lang.dispatchEvent(new Event('change'));}document.querySelector('#btn-new').click()`);
  assert.equal(await evaluate(`helpFrames.every((f,i)=>f===document.querySelectorAll('.pane iframe')[i])`),true,'Desktop help preserves terminals');
  const slots=await evaluate(`localStorage.getItem('orch_slots')`);
  await viewport(390,844);
  await cdp('Emulation.setTouchEmulationEnabled',{enabled:true});
  await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...await point(),id:1}]});
  await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await waitFor(`!document.querySelector('#new-standard-help').hidden`);
  assert.equal(await evaluate(`document.querySelector('#new-standard-help-toggle').getAttribute('aria-label')`),'会话选项说明');
  assert.ok(await evaluate(`document.querySelector('#new-standard-help').textContent.includes('原始记录只读')`));
  assert.equal(await evaluate(`(()=>{const r=document.querySelector('#new-standard-help').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;})()`),true,'Touch help stays in the viewport');
  await screenshot('new-session-help-touch-zh');
  const outside=await evaluate(`(()=>{const r=document.querySelector('#new-modal-title').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};})()`);
  await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...outside,id:1}]});
  await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await waitFor(`document.querySelector('#new-standard-help').hidden`);
  assert.equal(await evaluate(`document.querySelector('#new-modal').hidden`),false,'Outside help tap inside the form keeps the form open');
  await cdp('Emulation.setTouchEmulationEnabled',{enabled:false});
  await evaluate(`document.querySelector('#new-standard-help-toggle').click();document.querySelector('#new-close').click()`);
  assert.equal(await evaluate(`document.querySelector('#new-standard-help').hidden`),true,'Closing the form clears pinned help');
  assert.equal(await evaluate(`localStorage.getItem('orch_slots')`),slots);
  assert.equal(requests.filter(r=>r.method==='POST').length,writes,'Help never starts or changes a session');
  await viewport(1280,900);
  await evaluate(`{const lang=document.querySelector('[data-appearance="language"]');lang.value='en';lang.dispatchEvent(new Event('change'));}`);
  console.log('PASS: hidden session instructions, hover/focus/touch help, Escape and outside dismissal, bilingual content, viewport bounds and terminal preservation');
}
