import assert from 'node:assert/strict';

export async function checkSessionOptions({evaluate,waitFor,cdp,viewport,screenshot,pause,requests,groups,creations,mode,reply,finish}) {
  await waitFor(`!!document.querySelector('#pane-group-tabs')`);
  await viewport(1280,900);
  groups.groups=[{id:'options-project',name:'Project <sample>',color:'blue'}];
  await cdp('Page.reload');
  await waitFor(`document.querySelectorAll('.pane iframe').length===4 && [...document.querySelectorAll('.pane iframe')].every(f=>f.contentDocument?.querySelector('textarea'))`);
  await waitFor(`!!document.querySelector('[data-group-filter="options-project"]')`);
  await evaluate(`{const lang=document.querySelector('[data-appearance="language"]');lang.value='en';lang.dispatchEvent(new Event('change'));}`);
  await evaluate(`document.querySelector('[data-group-filter="options-project"]').click();document.querySelector('#btn-new').click()`);
  await waitFor(`document.querySelector('#new-group').value==='options-project'`);
  await evaluate(`document.querySelector('#new-close').click();document.querySelector('[data-group-filter="all"]').click();document.querySelector('#btn-new').click();document.querySelector('#new-agent').value='codex';document.querySelector('#new-agent').dispatchEvent(new Event('change'))`);
  await waitFor(`!!document.querySelector('#new-model-choice option[value="codex-live"]')`);
  assert.equal(await evaluate(`document.querySelector('#new-group').value`),'');
  assert.equal(await evaluate(`document.querySelector('#new-model-choice option[value="codex-live"]').textContent`),'Live model <sample> · codex-live');
  assert.equal(await evaluate(`document.querySelector('#new-model-choice sample')`),null,'Model labels render literally');
  await evaluate(`document.querySelector('#new-model-choice').value='codex-live';document.querySelector('#new-model-choice').dispatchEvent(new Event('change'));document.querySelector('#new-group').value='options-project';window.optionsFrames=[...document.querySelectorAll('.pane iframe')];`);
  const count=requests.filter(r=>r.path==='/api/models').length;
  await pause(1500);
  assert.equal(requests.filter(r=>r.path==='/api/models').length,count,'Polling does not launch repeated CLI queries');
  assert.equal(await evaluate(`document.querySelector('#new-model').value`),'codex-live');
  await screenshot('new-session-choices-en');
  const creationCount=creations.length;
  await evaluate(`document.querySelector('#new-submit-bg').click();document.querySelector('#new-submit-bg').click()`);
  for(let i=0;i<60&&creations.length===creationCount;i++) await pause(50);
  assert.equal(creations.length,creationCount+1,'One create request despite repeated click');
  assert.equal(creations.at(-1).group_id,'options-project');
  assert.equal(creations.at(-1).model,'codex-live');
  finish();
  await waitFor(`document.querySelector('#new-modal').hidden`);
  assert.equal(await evaluate(`optionsFrames.every((f,i)=>f===document.querySelectorAll('.pane iframe')[i])`),true,'Choices preserve existing terminals');
  mode('delay');
  await evaluate(`document.querySelector('#btn-new').click();document.querySelector('#new-agent').value='claude';document.querySelector('#new-agent').dispatchEvent(new Event('change'))`);
  for(let i=0;i<60&&!reply();i++) await pause(50);
  const delayed=reply();assert.ok(delayed);
  mode('ok');
  await evaluate(`document.querySelector('#new-agent').value='cursor';document.querySelector('#new-agent').dispatchEvent(new Event('change'))`);
  await waitFor(`!!document.querySelector('#new-model-choice option[value="cursor-live"]')`);
  delayed();await pause(200);
  assert.equal(await evaluate(`!!document.querySelector('#new-model-choice option[value="claude-live"]')`),false,'Late catalog cannot replace the selected agent');
  mode('fail');
  await evaluate(`document.querySelector('#new-model-refresh').click()`);
  await waitFor(`document.querySelector('#new-model-status').textContent.includes('unavailable')`);
  await evaluate(`document.querySelector('#new-model-choice').value='__custom__';document.querySelector('#new-model-choice').dispatchEvent(new Event('change'));document.querySelector('#new-model').value='my-provider/custom';`);
  assert.equal(await evaluate(`document.querySelector('#new-model').hidden`),false);
  await evaluate(`{const lang=document.querySelector('[data-appearance="language"]');lang.value='zh';lang.dispatchEvent(new Event('change'));}`);
  assert.equal(await evaluate(`document.querySelector('#new-group-label').textContent`),'项目分组');
  assert.equal(await evaluate(`document.querySelector('#new-model').value`),'my-provider/custom');
  await viewport(390,844);
  assert.equal(await evaluate(`document.querySelector('#new-group option[value=""]').textContent`),'未分组');
  assert.equal(await evaluate(`(()=>{const r=document.querySelector('#new-submit-bg').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;})()`),true,'Mobile submit remains visible with the added fields');
  assert.equal(await evaluate(`(()=>{const r=document.querySelector('#new-close').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;})()`),true,'Mobile close remains reachable');
  await screenshot('new-session-choices-zh-narrow');
  const before=requests.filter(r=>r.path==='/api/models').length;
  await evaluate(`document.querySelector('#new-agent').value='terminal';document.querySelector('#new-agent').dispatchEvent(new Event('change'))`);
  assert.equal(await evaluate(`document.querySelector('#new-model-field').hidden`),true);
  await pause(200);
  assert.equal(requests.filter(r=>r.path==='/api/models').length,before,'Terminal does not query AI models');
  await evaluate(`document.querySelector('#new-close').click();{const lang=document.querySelector('[data-appearance="language"]');lang.value='en';lang.dispatchEvent(new Event('change'));}`);
  mode('ok');await viewport(1280,900);
  console.log('PASS: creation group/default, live CLI dropdown, exact submitted model/group, custom fallback, stale catalog protection, bilingual narrow layout and frame preservation');
}
