const assert=require('node:assert/strict');
const fs=require('node:fs');
const timers=[];
global.window={};global.document={documentElement:{lang:'en'}};
global.localStorage={getItem:()=>null};
global.setInterval=fn=>{timers.push(fn);return timers.length;};
global.clearInterval=()=>{};
eval(fs.readFileSync('static/terminal-files.js','utf8'));
let context={id:'remote-1',host:'dev',cwd:'/remote'};
const calls=[],opens=[];
const api=async(url,options={})=>{
  calls.push({url,...options});
  if(url.endsWith('/file-context'))return {current:context,settings:{auto_discover:true},contexts:[context],configured:true};
  if(url.endsWith('/terminal-file'))return {folder:{path:'/cache/report.md'}};
  return {files:[],errors:[]};
};
const controller=window.SilingTerminalFiles.create({api,openViewer:async(...args)=>opens.push(args)});
let lines=['previous-report.md'];
const buffer={baseY:0,cursorY:0,type:'normal',get length(){return lines.length;},getLine:y=>({translateToString:()=>lines[y]||''})};
const handlers={};
const term={parser:{registerCsiHandler:({final},fn)=>{handlers[final]=fn;return{dispose(){}};}},rows:10,buffer:{active:buffer},registerMarker:offset=>({line:buffer.baseY+buffer.cursorY+offset,isDisposed:false,dispose(){this.isDisposed=true;}}),onWriteParsed:()=>({dispose(){}})};
let load;
const frame={dataset:{fileContext:'true'},isConnected:true,contentWindow:{term},addEventListener:(name,fn)=>load=fn};
const settle=()=>new Promise(resolve=>setTimeout(resolve,5));
(async()=>{
  controller.attach(frame,'fixture');load();await settle();
  assert.equal(frame.contentWindow.silingFileContextForRow(0),'','Preexisting output has unknown provenance');
  lines.push('report.md');buffer.cursorY=1;timers[0]();await settle();
  assert.equal(frame.contentWindow.silingFileContextForRow(1),'remote-1');
  assert.equal(calls.filter(c=>c.url.endsWith('/discover-files')).length,1);
  context={id:'local-2',host:'',cwd:'/local'};
  lines.push('new-report.md');buffer.cursorY=2;timers[0]();await settle();
  assert.equal(frame.contentWindow.silingFileContextForRow(1),'remote-1','Old remote output never gets relabeled on SSH exit');
  assert.equal(frame.contentWindow.silingFileContextForRow(2),'local-2');
  await controller.openPath('fixture','report.md',frame.contentWindow.silingFileContextForRow(1));
  assert.equal(calls.at(-1).body.context_id,'remote-1');
  assert.deepEqual(opens,[['fixture','/cache/report.md']]);
  const before=calls.filter(c=>c.url.endsWith('/discover-files')).length;
  timers[0]();await settle();
  assert.equal(calls.filter(c=>c.url.endsWith('/discover-files')).length,before,'Unchanged text is not discovered again');
  handlers.J([2]);timers[0]();await settle();
  assert.equal(frame.contentWindow.silingFileContextForRow(1),'','A redrawn line from a different host is ambiguous, never relabeled silently');
  buffer.type='alternate';lines.push('alternate-report.md');buffer.cursorY=3;timers[0]();await settle();
  assert.equal(frame.contentWindow.silingFileContextForRow(3),'local-2','tmux alternate buffer participates in file discovery');
  assert.ok(calls.some(call=>call.body?.automatic && call.body.text.includes('alternate-report.md')));
  frame.isConnected=false;timers[0]();
  console.log('PASS: output context ownership, automatic discovery, old-host click resolution and deduplication');
})().catch(error=>{console.error(error);process.exitCode=1;});
